#!/usr/bin/env bash
# Read /etc/passwd line by line
while IFS=: read -r username password user_id group_id full_name home_directory shell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $user_id."
done < /etc/passwd
